# Generated by Django 4.2.20 on 2025-05-24 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maquinaria", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("terrenos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha_realizacion", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("completada", "Completada"),
                            ("no_completada", "No completada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("motivo_no_completada", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "maquinas",
                    models.ManyToManyField(
                        related_name="tareas", to="maquinaria.maquinaria"
                    ),
                ),
                (
                    "terreno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas",
                        to="terrenos.terreno",
                    ),
                ),
                (
                    "trabajadores",
                    models.ManyToManyField(
                        related_name="tareas", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
