# Generated by Django 4.2.20 on 2025-06-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_telefono"),
        ("tareas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarea",
            name="cuadrillas",
            field=models.ManyToManyField(
                blank=True, related_name="tareas", to="users.cuadrilla"
            ),
        ),
    ]
