# Generated by Django 4.2.20 on 2025-05-01 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telefono",
            field=models.CharField(
                help_text="Formato: +34600606060 o 600606060",
                max_length=12,
                validators=[django.core.validators.RegexValidator("^\\d{9}$")],
            ),
        ),
    ]
